language: python
python:
  - 3.7

install:
  - pip install python-semantic-release

script: 
  - echo "Hello!"

after_success:
  - git config --global user.name "semantic-release (via TravisCI)"
  - git config --global user.email "semantic-release@travis"
  - pip install python-semantic-release
  - semantic-release publish