sudo: required
language: python
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - git config --global user.name "semantic-release (via TravisCI)"
          - git config --global user.email "semantic-release@travis"
          - pip install python-semantic-release
          - semantic-release publish
        